[template]

# The name of the template that will be used to render the application's configuration file
# Confd will look in `/etc/conf.d/templates` for these files by default
src = "storage.tmpl"

# The location to place the rendered configuration file
dest = "/config/storage.yml"

# The etcd keys or directory to watch.  This is where the information to fill in
# the template will come from.
keys = [ "/dtr/configs/storage.yml" ]

# File ownership and mode information
owner = "root"
mode = "0644"

# These are the commands that will be used to check whether the rendered config is
# valid and to reload the actual service once the new config is in place
# TODO: can registry configs be reloaded without restarting thee container?
reload_cmd = "killall -USR2 registry"
