name: e2e

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: set up docker
        uses: docker-practice/actions-setup-docker@1.0.7
        with:
          docker_version: 18.09
          docker_channel: stable

      - name: checkout distribution
        uses: actions/checkout@master
        with:
          path: main

      - name: start distribution server
        run: |
          IP=`hostname -I | awk '{print $1}'`
          echo "IP=$IP" >> $GITHUB_ENV
          echo '{"insecure-registries" : ["'$IP':5000"]}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
          DISTRIBUTION_REF="local-distribution:v$(date +%Y%m%d%H%M%S)"
          cd ./main
          docker build -f ./Dockerfile -t "${DISTRIBUTION_REF}" .
          docker run --rm -p 5000:5000 -p 5001:5001 -idt "${DISTRIBUTION_REF}"

      - name: script
        run: |
          bash ./main/tests/push.sh $IP
